name: Build and Publish

on:
  pull_request:

jobs:
  build-and-test-pullrequest:
    name: Build Docker image and test for Pull Requests
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          prefix: SLUG_

      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image and Load to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            test-image
          load: true
      - name: Test Image
        run: |
          docker run --rm test-image /bin/bash -c "robo test:ci"
